Repository SpartaFinalProject/Dang, pull requests merged in 2023-10, with the labels that each got.

#12 [DESIGN] Shelter
  .DS_Store
  app/.idea/inspectionProfiles/Project_Default.xml
  app/app/src/main/res/drawable/background_btn_gray.xml
  app/app/src/main/res/drawable/background_btn_long_red.xml
  app/app/src/main/res/drawable/background_btn_red.xml
  app/app/src/main/res/drawable/background_btn_white.xml
  app/app/src/main/res/drawable/background_dialog.xml
  app/app/src/main/res/drawable/background_edittext.xml
  app/app/src/main/res/drawable/background_item.xml
  app/app/src/main/res/drawable/background_item_detail_img_radius.xml
  app/app/src/main/res/drawable/background_item_img_radius.xml
  app/app/src/main/res/drawable/icon_heart_empty.xml
  app/app/src/main/res/drawable/icon_heart_filled.xml
  app/app/src/main/res/drawable/icon_like_off.xml
  app/app/src/main/res/drawable/icon_like_on.xml
  app/app/src/main/res/layout/dialog_shelter_select_location_detail.xml
  app/app/src/main/res/layout/dialog_shelter_select_location_main.xml
  app/app/src/main/res/layout/fragment_home.xml
  app/app/src/main/res/layout/fragment_shelter.xml
  app/app/src/main/res/layout/fragment_shelter_detail.xml
  app/app/src/main/res/layout/fragment_shelter_result.xml
  app/app/src/main/res/layout/item_common_detail.xml
  app/app/src/main/res/values/colors.xml
Labels: 🎨 UI

#14 [DESIGN] fragment_dictionary
  app/app/src/main/res/drawable/background_search.xml
  app/app/src/main/res/layout/fragment_dictionary.xml
Labels: 🎨 UI

#15 [DESIGN] Search
  app/app/src/main/res/drawable/background_btn_red_no_padding.xml
  app/app/src/main/res/drawable/background_btn_white_no_padding.xml
  app/app/src/main/res/drawable/background_dialog_edittext.xml
  app/app/src/main/res/drawable/background_dialog_half.xml
  app/app/src/main/res/drawable/background_search_tag.xml
  app/app/src/main/res/drawable/icon_arrow_down.xml
  app/app/src/main/res/drawable/icon_female.xml
  app/app/src/main/res/drawable/icon_female_gray.xml
  app/app/src/main/res/drawable/icon_male.xml
  app/app/src/main/res/drawable/icon_male_gray.xml
  app/app/src/main/res/drawable/icon_neutrality.xml
  app/app/src/main/res/drawable/icon_neutrality_gray.xml
  app/app/src/main/res/layout/dialog_search_age.xml
  app/app/src/main/res/layout/dialog_search_gender.xml
  app/app/src/main/res/layout/dialog_search_size.xml
  app/app/src/main/res/layout/fragment_dog_detail.xml
  app/app/src/main/res/layout/fragment_search.xml
  app/app/src/main/res/layout/item_common_detail.xml
Labels: 🎨 UI

#18 Feature/11 pretestactivity
  app/app/build.gradle.kts
  app/app/src/main/AndroidManifest.xml
  app/app/src/main/java/com/android/dang/App.kt
  app/app/src/main/java/com/android/dang/MainActivity.kt
  app/app/src/main/java/com/android/dang/common/Constants.kt
  app/app/src/main/java/com/android/dang/pretest/PretestActivity.kt
  app/app/src/main/java/com/android/dang/pretest/PretestDialog.kt
  app/app/src/main/java/com/android/dang/util/SharedPref.kt
  app/app/src/main/res/drawable/background_btn_long_gray.xml
  app/app/src/main/res/drawable/background_btn_long_white.xml
  app/app/src/main/res/drawable/background_btn_red_nopadding.xml
  app/app/src/main/res/drawable/background_pretest_dialog.xml
  app/app/src/main/res/drawable/background_pretest_testview.xml
  app/app/src/main/res/drawable/background_pretest_testview_nopadding.xml
  app/app/src/main/res/drawable/icon_dog1.png
  app/app/src/main/res/drawable/selector_gray_to_white.xml
  app/app/src/main/res/drawable/selector_red_to_white.xml
  app/app/src/main/res/drawable/selector_text_press_basic.xml
  app/app/src/main/res/drawable/selector_text_press_white.xml
  app/app/src/main/res/drawable/selector_white_to_red.xml
  app/app/src/main/res/layout/activity_pretest.xml
  app/app/src/main/res/layout/dialog_pretest.xml
  app/app/src/main/res/raw/animation_lny9u46m.json
  app/app/src/main/res/raw/animation_lnylvk56.json
  app/app/src/main/res/values/strings.xml
  app/app/src/main/res/values/styles.xml
Labels: 🖥️ feature, 🎨 UI

#26 [FEATURE] header
  app/app/src/main/java/com/android/dang/MainActivity.kt
  app/app/src/main/java/com/android/dang/home/HomeFragment.kt
  app/app/src/main/res/layout/activity_main.xml
  app/app/src/main/res/layout/header.xml
Labels: 🖥️ feature

#29 [FEATURE] search api
  app/app/build.gradle.kts
  app/app/src/main/AndroidManifest.xml
  app/app/src/main/java/com/android/dang/retrofit/Constants.kt
  app/app/src/main/java/com/android/dang/retrofit/DangClient.kt
  app/app/src/main/java/com/android/dang/retrofit/Interface.kt
  app/app/src/main/java/com/android/dang/retrofit/abandonedDog/AbandonedDog.kt
  app/app/src/main/java/com/android/dang/retrofit/kind/Kind.kt
  app/app/src/main/java/com/android/dang/search/SearchFragment.kt
  app/app/src/main/java/com/android/dang/search/adapter/RecentAdapter.kt
  app/app/src/main/java/com/android/dang/search/adapter/SearchAdapter.kt
  app/app/src/main/java/com/android/dang/search/searchItemModel/SearchDogData.kt
  app/app/src/main/java/com/android/dang/search/searchViewModel/RecentViewModel.kt
  app/app/src/main/java/com/android/dang/search/searchViewModel/SearchViewModel.kt
  app/app/src/main/res/drawable/ic_cancel.xml
  app/app/src/main/res/drawable/ic_time.xml
  app/app/src/main/res/layout/dialog_search_age.xml
  app/app/src/main/res/layout/dialog_search_gender.xml
  app/app/src/main/res/layout/dialog_search_size.xml
  app/app/src/main/res/layout/fragment_search.xml
  app/app/src/main/res/layout/item_common_detail.xml
  app/app/src/main/res/layout/item_recycler_view_recent_word.xml
Labels: 🖥️ feature

#31 [Feature] shelterfragment Map
  app/app/build.gradle.kts
  app/app/src/main/AndroidManifest.xml
  app/app/src/main/java/com/android/dang/MainActivity.kt
  app/app/src/main/java/com/android/dang/retrofit/Constants.kt
  app/app/src/main/java/com/android/dang/retrofit/Interface.kt
  app/app/src/main/java/com/android/dang/retrofit/abandonedDog/AbandonedDog.kt
  app/app/src/main/java/com/android/dang/retrofit/abandonedDog/AbandonedDogRes.kt
  app/app/src/main/java/com/android/dang/retrofit/abandonedDog/AbandonedShelter.kt
  app/app/src/main/java/com/android/dang/retrofit/kind/Body.kt
  app/app/src/main/java/com/android/dang/retrofit/kind/Items.kt
  app/app/src/main/java/com/android/dang/retrofit/kind/Kind.kt
  app/app/src/main/java/com/android/dang/retrofit/kind/Response.kt
  app/app/src/main/java/com/android/dang/retrofit/sido/Sido.kt
  app/app/src/main/java/com/android/dang/retrofit/sido/SidoResponse.kt
  app/app/src/main/java/com/android/dang/search/SearchFragment.kt
  app/app/src/main/java/com/android/dang/shelter/view/ShelterFragment.kt
  app/app/src/main/java/com/android/dang/shelter/view/SidoDialog.kt
  app/app/src/main/java/com/android/dang/shelter/view/SidoRecyclerViewAdapter.kt
  app/app/src/main/java/com/android/dang/shelter/view/SidoRecyclerViewHolder.kt
  app/app/src/main/java/com/android/dang/shelter/vm/ShelterViewModel.kt
  app/app/src/main/res/drawable/icon_pink_marker.png
  app/app/src/main/res/drawable/icon_window_body.png
  app/app/src/main/res/drawable/icon_window_tail.png
  app/app/src/main/res/layout/dialog_sido.xml
  app/app/src/main/res/layout/fragment_shelter.xml
  app/app/src/main/res/layout/item_sido.xml
  app/settings.gradle.kts
Labels: 🖥️ feature

#32 [FIX] Mainactivity_backstack 백키 누를 때, 백스택 적용 및 네비메뉴 동기화
  app/app/src/main/java/com/android/dang/MainActivity.kt
  app/app/src/main/res/layout/activity_main.xml
  app/app/src/main/res/navigation/nav_graph.xml
Labels: 🛠️ fix

#33 [Feature] Dictionaryfragment
  app/app/build.gradle.kts
  app/app/src/main/java/com/android/dang/BlankFragment4.kt
  app/app/src/main/java/com/android/dang/MainActivity.kt
  app/app/src/main/java/com/android/dang/dictionary/BindingAdapter.kt
  app/app/src/main/java/com/android/dang/dictionary/BreedsSpinnerAdapter.kt
  app/app/src/main/java/com/android/dang/dictionary/DictionaryFragment.kt
  app/app/src/main/java/com/android/dang/dictionary/DictionaryListAdapter.kt
  app/app/src/main/java/com/android/dang/dictionary/data/BreedItem.kt
  app/app/src/main/java/com/android/dang/dictionary/data/BreedsData.kt
  app/app/src/main/java/com/android/dang/dictionary/data/BreedsSpinnerData.kt
  app/app/src/main/java/com/android/dang/dictionary/retrofit/NetWorkClient.kt
  app/app/src/main/java/com/android/dang/dictionary/retrofit/NetWorkInterface.kt
  app/app/src/main/res/drawable/background_search_no_padding.xml
  app/app/src/main/res/drawable/item_spinner_dropdown_ripple.xml
  app/app/src/main/res/drawable/selector_editcolor_to_ripple.xml
  app/app/src/main/res/layout/fragment_blank4.xml
  app/app/src/main/res/layout/fragment_dictionary.xml
  app/app/src/main/res/layout/item_dictionary.xml
  app/app/src/main/res/layout/item_dictionary_spinner.xml
  app/app/src/main/res/layout/item_dictionary_spinner_drop.xml
Labels: 🖥️ feature, 🎨 UI

#39 [FEATURE] HomeFragment
  app/.idea/deploymentTargetDropDown.xml
  app/app/build.gradle.kts
  app/app/src/main/java/com/android/dang/MainActivity.kt
  app/app/src/main/java/com/android/dang/home/HomeFragment.kt
  app/app/src/main/java/com/android/dang/home/homeAdapter/HomeAdapter.kt
  app/app/src/main/java/com/android/dang/like/LikeAdapter.kt
  app/app/src/main/java/com/android/dang/like/LikeFragment.kt
  app/app/src/main/java/com/android/dang/util/PrefManager.kt
  app/app/src/main/java/com/android/dang/util/SharedPref.kt
  app/app/src/main/res/layout/activity_main.xml
  app/app/src/main/res/layout/fragment_like.xml
Labels: 🖥️ feature

#41 [FEATURE] search-api
  app/app/src/main/AndroidManifest.xml
  app/app/src/main/java/com/android/dang/MainActivity.kt
  app/app/src/main/java/com/android/dang/detailFragment/DogDetailFragment.kt
  app/app/src/main/java/com/android/dang/search/SearchFragment.kt
  app/app/src/main/java/com/android/dang/search/adapter/RecentAdapter.kt
  app/app/src/main/java/com/android/dang/search/adapter/SearchAdapter.kt
  app/app/src/main/java/com/android/dang/search/searchItemModel/SearchDogData.kt
  app/app/src/main/java/com/android/dang/search/searchViewModel/RecentViewModel.kt
  app/app/src/main/res/layout/fragment_search.xml
  app/app/src/main/res/values/strings.xml
Labels: 🖥️ feature
