Repository SpartaFinalProject/Dang, pull requests merged in 2023-11, with the labels that each got.

#43 [Like-Fragment] 아이템 스와이프 삭제 및 삭제 시 homeFragment true/false 반영
  app/app/src/main/java/com/android/dang/home/HomeFragment.kt
  app/app/src/main/java/com/android/dang/home/homeAdapter/HomeAdapter.kt
  app/app/src/main/java/com/android/dang/home/retrofit/HomeData.kt
  app/app/src/main/java/com/android/dang/like/LikeAdapter.kt
  app/app/src/main/java/com/android/dang/like/LikeFragment.kt
  app/app/src/main/java/com/android/dang/like/Swipe.kt
  app/app/src/main/java/com/android/dang/search/SearchFragment.kt
  app/app/src/main/java/com/android/dang/search/searchItemModel/SearchDogData.kt
  app/app/src/main/java/com/android/dang/util/PrefManager.kt
Labels: 🖥️ feature

#44 [FIX] layout
  app/app/src/main/res/drawable/background_btn_red.xml
  app/app/src/main/res/drawable/icon_like_on.xml
Labels: 🎨 UI, 🛠️ fix

#50 [HOME,LIKE,DETAIL] 기능추가
  .DS_Store
  .idea/workspace.xml
  app/.idea/deploymentTargetDropDown.xml
  app/app/src/main/java/com/android/dang/MainActivity.kt
  app/app/src/main/java/com/android/dang/detailFragment/DogDetailFragment.kt
  app/app/src/main/java/com/android/dang/home/homeAdapter/HomeAdapter.kt
  app/app/src/main/java/com/android/dang/home/retrofit/HomeData.kt
  app/app/src/main/java/com/android/dang/like/LikeAdapter.kt
  app/app/src/main/java/com/android/dang/search/SearchFragment.kt
  app/app/src/main/java/com/android/dang/search/searchItemModel/SearchDogData.kt
  app/app/src/main/res/drawable/background_search.xml
  app/app/src/main/res/layout/fragment_dog_detail.xml
  app/app/src/main/res/layout/fragment_search.xml
  app/app/src/main/res/layout/item_recycler_view_recent_word.xml
Labels: 🖥️ feature, 🎨 UI, 🛠️ fix

#51 Feature/19 dictionaryfragment
  app/app/src/main/java/com/android/dang/MainActivity.kt
  app/app/src/main/java/com/android/dang/common/Constants.kt
  app/app/src/main/java/com/android/dang/dictionary/BindingAdapter.kt
  app/app/src/main/java/com/android/dang/dictionary/DictionaryFragment.kt
  app/app/src/main/java/com/android/dang/dictionary/DictionaryListAdapter.kt
  app/app/src/main/java/com/android/dang/dictionary/OnDictionaryListener.kt
  app/app/src/main/java/com/android/dang/dictionary/data/BreedTranslation.kt
  app/app/src/main/java/com/android/dang/dictionary/data/BreedsData.kt
  app/app/src/main/java/com/android/dang/dictionary/data/TemperamentTranslation.kt
  app/app/src/main/java/com/android/dang/dictionary/retrofit/NetWorkClient.kt
  app/app/src/main/java/com/android/dang/dictionary/retrofit/NetWorkInterface.kt
  app/app/src/main/java/com/android/dang/pretest/PretestActivity.kt
  app/app/src/main/java/com/android/dang/search/SearchFragment.kt
  app/app/src/main/res/drawable/icon_arrowup_circle.png
  app/app/src/main/res/drawable/scrollbar_line.xml
  app/app/src/main/res/drawable/scrollbar_line_drawable.xml
  app/app/src/main/res/drawable/scrollbar_thumb.xml
  app/app/src/main/res/drawable/scrollbar_thumb_drawable.xml
  app/app/src/main/res/layout/activity_pretest.xml
  app/app/src/main/res/layout/dialog_pretest.xml
  app/app/src/main/res/layout/fragment_dictionary.xml
  app/app/src/main/res/layout/item_dictionary.xml
  app/app/src/main/res/values/strings.xml
  app/app/src/main/res/values/styles.xml
Labels: 🖥️ feature, 🎨 UI, 🛠️ fix, ⛘ merge

#54 [Home-page, Detail-page] 좋아요 기능 및 디테일 페이지 이동 기능 추가
  app/app/src/main/java/com/android/dang/MainActivity.kt
  app/app/src/main/java/com/android/dang/detailFragment/DogDetailFragment.kt
  app/app/src/main/java/com/android/dang/home/HomeFragment.kt
  app/app/src/main/java/com/android/dang/home/homeAdapter/HomeAdapter.kt
  app/app/src/main/java/com/android/dang/like/LikeAdapter.kt
  app/app/src/main/java/com/android/dang/like/LikeFragment.kt
  app/app/src/main/java/com/android/dang/like/LikeViewModel.kt
  app/app/src/main/java/com/android/dang/retrofit/Interface.kt
  app/app/src/main/java/com/android/dang/retrofit/abandonedDog/AbandonedDog.kt
  app/app/src/main/java/com/android/dang/search/LikeList.kt
  app/app/src/main/java/com/android/dang/search/SearchFragment.kt
  app/app/src/main/java/com/android/dang/search/adapter/RecentAdapter.kt
  app/app/src/main/java/com/android/dang/search/adapter/SearchAdapter.kt
  app/app/src/main/java/com/android/dang/search/searchViewModel/RecentViewModel.kt
  app/app/src/main/java/com/android/dang/search/searchViewModel/SearchViewModel.kt
  app/app/src/main/java/com/android/dang/util/PrefManager.kt
  app/app/src/main/java/com/android/dang/util/SharedPref.kt
  app/app/src/main/res/layout/fragment_search.xml
Labels: 🖥️ feature

#56 [Shelter-result] 보호중인 유기견 마릿수 확인 & 보호소 결과 페이지 리싸이클러뷰 아이템 추가
  app/app/src/main/java/com/android/dang/MainActivity.kt
  app/app/src/main/java/com/android/dang/MainViewModel.kt
  app/app/src/main/java/com/android/dang/retrofit/Interface.kt
  app/app/src/main/java/com/android/dang/retrofit/shelter/Shelter.kt
  app/app/src/main/java/com/android/dang/retrofit/shelter/ShelterRes.kt
  app/app/src/main/java/com/android/dang/shelter/shelterresult/DogItemViewHolder.kt
  app/app/src/main/java/com/android/dang/shelter/shelterresult/ShelterResultAdapter.kt
  app/app/src/main/java/com/android/dang/shelter/shelterresult/ShelterResultFragment.kt
  app/app/src/main/java/com/android/dang/shelter/view/ShelterFragment.kt
  app/app/src/main/java/com/android/dang/shelter/vm/ShelterViewModel.kt
  app/app/src/main/res/layout/fragment_dog_detail.xml
  app/app/src/main/res/layout/fragment_shelter.xml
  app/app/src/main/res/values/strings.xml
Labels: 🖥️ feature

#59 [FIX] 클릭이벤트 오류 수정
  app/app/src/main/java/com/android/dang/MainActivity.kt
  app/app/src/main/java/com/android/dang/home/HomeFragment.kt
  app/app/src/main/java/com/android/dang/home/OnBannerListener.kt
Labels: 🛠️ fix

#60 LikeFragment - 디테일 페이지 이동 기능 추가
  app/app/src/main/java/com/android/dang/MainActivity.kt
  app/app/src/main/java/com/android/dang/detailFragment/DogDetailFragment.kt
  app/app/src/main/java/com/android/dang/like/LikeAdapter.kt
  app/app/src/main/java/com/android/dang/like/LikeFragment.kt
  app/app/src/main/java/com/android/dang/search/SearchFragment.kt
  app/app/src/main/java/com/android/dang/search/adapter/SearchAdapter.kt
  app/app/src/main/res/drawable/icon_heart_empty.xml
  app/app/src/main/res/layout/fragment_search.xml
Labels: 🖥️ feature, 🛠️ fix

#61 [Splashactivity&SearchFragment] 앱아이콘, 스플래쉬화면 추가, 서치페이지 수정
  app/app/src/main/AndroidManifest.xml
  app/app/src/main/dang_launcher-playstore.png
  app/app/src/main/java/com/android/dang/MainActivity.kt
  app/app/src/main/java/com/android/dang/SplashActivity.kt
  app/app/src/main/java/com/android/dang/retrofit/abandonedDog/Header.kt
  app/app/src/main/java/com/android/dang/search/SearchFragment.kt
  app/app/src/main/res/drawable/bg.xml
  app/app/src/main/res/drawable/dang_launcher_foreground.xml
  app/app/src/main/res/layout/activity_splash.xml
  app/app/src/main/res/layout/fragment_dictionary.xml
  app/app/src/main/res/layout/fragment_dog_detail.xml
  app/app/src/main/res/mipmap-anydpi-v26/dang_launcher.xml
  app/app/src/main/res/mipmap-anydpi-v26/dang_launcher_round.xml
  app/app/src/main/res/mipmap-hdpi/dang_launcher.webp
  app/app/src/main/res/mipmap-hdpi/dang_launcher_round.webp
  app/app/src/main/res/mipmap-mdpi/dang_launcher.webp
  app/app/src/main/res/mipmap-mdpi/dang_launcher_round.webp
  app/app/src/main/res/mipmap-xhdpi/dang_launcher.webp
  app/app/src/main/res/mipmap-xhdpi/dang_launcher_round.webp
  app/app/src/main/res/mipmap-xxhdpi/dang_launcher.webp
  app/app/src/main/res/mipmap-xxhdpi/dang_launcher_round.webp
  app/app/src/main/res/mipmap-xxxhdpi/dang_launcher.webp
  app/app/src/main/res/mipmap-xxxhdpi/dang_launcher_round.webp
  app/app/src/main/res/values/colors.xml
  app/app/src/main/res/xml/activity_splash_scene.xml
Labels: 🖥️ feature, 🎨 UI, 🛠️ fix, ⛘ merge

#63 [DESIGN] : 🎨(feature/53-splashactivity): 로딩 Lottie애니메이션 추가
  app/app/src/main/res/layout/fragment_dictionary.xml
  app/app/src/main/res/raw/animation_loading.json
Labels: 🎨 UI, ⛘ merge

#64 [Shelter-result] 좋아요 기능 추가 및 exception 해결
  app/app/src/main/java/com/android/dang/MainActivity.kt
  app/app/src/main/java/com/android/dang/MainViewModel.kt
  app/app/src/main/java/com/android/dang/detailFragment/DogDetailFragment.kt
  app/app/src/main/java/com/android/dang/home/homeAdapter/HomeAdapter.kt
  app/app/src/main/java/com/android/dang/like/LikeAdapter.kt
  app/app/src/main/java/com/android/dang/retrofit/abandonedDog/AbandonedDogRes.kt
  app/app/src/main/java/com/android/dang/retrofit/abandonedDog/AbandonedShelter.kt
  app/app/src/main/java/com/android/dang/retrofit/abandonedDog/Header.kt
  app/app/src/main/java/com/android/dang/retrofit/abandonedDog/Response.kt
  app/app/src/main/java/com/android/dang/retrofit/abandonedDog/SearchDogData.kt
  app/app/src/main/java/com/android/dang/search/SearchFragment.kt
  app/app/src/main/java/com/android/dang/search/adapter/SearchAdapter.kt
  app/app/src/main/java/com/android/dang/search/searchItemModel/SearchDogData.kt
  app/app/src/main/java/com/android/dang/search/searchViewModel/SearchViewModel.kt
  app/app/src/main/java/com/android/dang/shelter/shelterresult/DogItemViewHolder.kt
  app/app/src/main/java/com/android/dang/shelter/shelterresult/ShelterResultAdapter.kt
  app/app/src/main/java/com/android/dang/shelter/shelterresult/ShelterResultFragment.kt
  app/app/src/main/java/com/android/dang/shelter/view/ShelterFragment.kt
  app/app/src/main/java/com/android/dang/shelter/vm/ShelterViewModel.kt
  app/app/src/main/res/layout/fragment_dog_detail.xml
  app/app/src/main/res/layout/fragment_shelter.xml
  app/app/src/main/res/layout/fragment_shelter_result.xml
Labels: 🖥️ feature, 🛠️ fix

#65 [Home-page] 프로그래스 바 추가, retry 추가
  app/app/src/main/java/com/android/dang/home/HomeFragment.kt
  app/app/src/main/res/layout/fragment_home.xml
Labels: 🖥️ feature

#66 댕댕백과에서 서치화면 이동시 조회 수정, 상세화면 호출코드 수정
  app/app/src/main/java/com/android/dang/MainActivity.kt
  app/app/src/main/java/com/android/dang/search/SearchFragment.kt
  app/app/src/main/res/layout/fragment_dog_detail.xml
Labels: 🖥️ feature, 🛠️ fix

#67 HomeFragment, SearchFragment에서 크래시 수정
  app/app/src/main/java/com/android/dang/home/HomeFragment.kt
  app/app/src/main/java/com/android/dang/search/SearchFragment.kt
Labels: 🛠️ fix

#68 [Shelter-result] 디테일 페이지 이동 기능 추가
  app/app/src/main/java/com/android/dang/MainViewModel.kt
  app/app/src/main/java/com/android/dang/home/HomeFragment.kt
  app/app/src/main/java/com/android/dang/shelter/shelterresult/ShelterResultAdapter.kt
  app/app/src/main/java/com/android/dang/shelter/shelterresult/ShelterResultFragment.kt
  app/app/src/main/java/com/android/dang/shelter/view/ShelterFragment.kt
  app/app/src/main/java/com/android/dang/shelter/vm/ShelterViewModel.kt
  app/app/src/main/res/layout/fragment_shelter.xml
Labels: 🖥️ feature

#69 [Shelter] 프로그래스바 추가 & 오류 수정
  app/app/build.gradle.kts
  app/app/src/main/java/com/android/dang/retrofit/Interface.kt
  app/app/src/main/java/com/android/dang/shelter/view/ShelterFragment.kt
  app/app/src/main/java/com/android/dang/shelter/vm/ShelterViewModel.kt
  app/app/src/main/res/drawable/icon_pink_marker2.png
  app/app/src/main/res/layout/fragment_shelter.xml
Labels: 🖥️ feature, 🛠️ fix
